export default {
    OPEN_FILE: "OPEN_FILE",
    OPEN_DIR: "OPEN_DIR",
    OPEN_WORKSPACE: "OPEN_WORKSPACE",
    CREATE_TREE: "CREATE_TREE",
    CREATE_NODE: "CREATE_NODE",
    DELETE_NODE: "DELETE_NODE",
    COPY_NODE: "COPY_NODE",
    PASTE_NODE: "PASTE_NODE",
    SAVE: "SAVE",
    SAVE_ALL: "SAVE_ALL",
};
